mysite/board/urls.py
from django.urls import path

from board import views

app_name = "board"

urlpatterns = [
    path("", views.board_list, name="list"),
    path("create/", views.board_create, name="create"),
    path("<int:board_id>/", views.board_read, name="read"),
    path("<int:board_id>/delete/", views.board_delete, name="delete"),
    path("<int:board_id>/update/", views.board_update, name="update"),
]

mysite/common/urls.py
from django.urls import path

from common import views

app_name = "common"

urlpatterns = [
    path('login/', views.common_login, name='login'),
    path('logout/', views.common_logout, name='logout'),
    path('profile/', views.common_profile, name='profile'),
    path('password/', views.common_password, name='password'),
    path('register/', views.common_register, name='register'),
    path('find_username/', views.common_find_username, name='find_username'),
    path('reset_password/', views.common_reset_password, name='reset_password'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from common import views as common_views
from django.conf import settings
from django.conf.urls.static import static

def trigger_error(request):
    division_by_zero = 1 / 0
    
urlpatterns = [
    path('sentry-debug/', trigger_error),
    path("", common_views.main_page, name="main_page"),
    path('summernote/', include('django_summernote.urls')),
    path("admin/", admin.site.urls),
    path("common/", include("common.urls")),
    path("common2/", include("common2.urls")),
    path("board/", include("board.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/templates/base.html
<!doctype html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <title>커뮤니티</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <style>
            /*
            body {
                margin-top: 50px;
            }
            */
        </style>
    </head>
    <body>
        <!-- navbar -->
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="#">커뮤니티</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'board:list' %}">게시판</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav d-flex">
                        <!-- 환영 인사 -->
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="nav-link">{{ user.first_name }}님 반갑습니다.</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'common:profile' %}">프로필</a>
                        </li>
                        {% endif %}
                        <!--//  환영 인사 -->

                        <!-- 로그인/로그아웃 -->
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="{% url 'common:logout' %}">로그아웃</a>
                            {% else %}
                                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                            {% endif %}
                        </li>
                        <!--// 로그인/로그아웃 -->

                        <!-- 회원가입 -->
                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'common:register' %}">회원가입</a>
                        </li>
                        {% endif %}
                        <!--// 회원가입 -->
                    </ul>
                </div>
            </div>
        </nav>
        <!--// navbar -->

        <div class="container mt-5">
            <!-- 메시지 -->
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == "error" %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% elif message.tags == "success" %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <!--// 메시지 -->

            {% block content %}
            {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
        {% block script %}
        {% endblock %}
    </body>
</html>