mysite/board/urls.py
from django.urls import path

from board import views

app_name = "board"

urlpatterns = [
    path("", views.board_list, name="list"),
    path("create/", views.board_create, name="create"),
    path("<int:board_id>/", views.board_read, name="read"),
    path("<int:board_id>/delete/", views.board_delete, name="delete"),
    path("<int:board_id>/update/", views.board_update, name="update"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from common import views as common_views
from django.conf import settings
from django.conf.urls.static import static

def trigger_error(request):
    division_by_zero = 1 / 0
    
urlpatterns = [
    path('sentry-debug/', trigger_error),
    path("", common_views.main_page, name="main_page"),
    path('summernote/', include('django_summernote.urls')),
    path("admin/", admin.site.urls),
    path("common/", include("common.urls")),
    path("common2/", include("common2.urls")),
    path("board/", include("board.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/board/models.py
from django.db import models
from django.contrib.auth.models import User

class Board(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    summary = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

mysite/board/forms.py
from django import forms
from django.utils.safestring import SafeString
from board.models import Board
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

# 등록
class CreateForm(forms.ModelForm):
    """
    def __init__(self, *args, **kwargs):
        super(CreateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            
    def as_div(self):
        return SafeString(super().as_div().replace("<div>", "<div class='mb-3'>"))
    """
    
    class Meta:
        model = Board
        fields = ["title", "content"]
        labels = {
            "title": "제목",
            "content": "내용",
        }
        widgets = {
            "content": SummernoteWidget(attrs={"summernote": {"width": "100%"}}),
        }

mysite/board/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
from django.utils.safestring import mark_safe
from django.contrib.auth import logout, authenticate, login
from board.models import Board
from board.forms import CreateForm
import os 
from openai import OpenAI


# 요약하기
def summary(content):
    client = OpenAI(api_key = os.environ.get("OPENAI_API_KEY"))
    
    system_content = """당신은 고급 텍스트 요약 전문가입니다. 사용자로부터 입력받은 긴 텍스트를 간결하고 이해하기 쉬운 요약본으로 변환하는 것이 주된 역할입니다. 요약할 때는 중요한 정보를 빠뜨리지 않도록 주의하고, 핵심 내용만을 포함하도록 하십시오. 모든 요약은 중립적이고 명확하게 작성하며, 가능한 한 사용자가 원문에서 얻고자 하는 주요 메시지와 정보를 포함하도록 합니다. 필요에 따라 문체를 적절하게 유지하면서도 길이를 줄여야 합니다. 답변은 한국말로 하세요."""
    
    completion = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_content},
            {"role": "user", "content": content}
        ]
    )

    return completion.choices[0].message.content

# 목록, /board/
def board_list(request):
    # 페이지 번호
    page = request.GET.get("page", 1)
    
    # 목록
    b_list = Board.objects.all().order_by("-created_at")
    
    # 검색
    kw = request.GET.get("kw", "")
    where = request.GET.get("where", "")
    
    if kw and where == "all":
        b_list = b_list.filter(
            Q(title__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) # 내용검색
        ).distinct()
    elif kw and where == "title":
        b_list = b_list.filter(
            Q(title__icontains=kw)
        ).distinct()
    elif kw and where == "content":
        b_list = b_list.filter(
            Q(content__icontains=kw)
        ).distinct()
    
    # 한페이지에 10개씩 보여주기
    paginator = Paginator(b_list, 10)
    page_obj = paginator.get_page(page)
    
    context = {
        "board_list": page_obj,
        "kw": kw,
        "where": where,
        "page": page,
    }
    return render(request, "board/list.html", context)


# 등록, /board/create/
def board_create(request):
    # 페이지 번호
    page = request.GET.get("page", 1)
    
    # 등록 폼   
    form = CreateForm()
    
    # 템플릿으로 넘겨줄 정보
    context = {
        "page": page,
        "form": form,
    }
    
    # POST
    if request.method == "POST":       
        # 등록 폼   
        form = CreateForm(request.POST)
        
        # 넘어온 값 검증
        if form.is_valid():
            cd = form.cleaned_data
            
            # 요약하기
            content_summary = summary(cd["content"])
            
            # 등록하기
            b = Board.objects.create(
                title=cd["title"], 
                content=cd["content"], 
                summary = content_summary,
                author=request.user
            )
            b.save()
            
            # 메시지
            messages.success(request, "게시글이 등록되었습니다.")
            
            # 보기로 이동
            return redirect("board:read", b.id)    
    
    # 등록 화면
    return render(request, "board/create.html", context)

# 보기, /board/<board_id>/
def board_read(request, board_id):
    # 페이지 번호
    page = request.GET.get("page", 1)
    
    # 게시글
    b = get_object_or_404(Board, pk=board_id)
    
    context = {
        "page": page,
        "board": b,    
    }
    
    return render(request, "board/read.html", context)

# 삭제, /board/<board_id>/delete/
def board_delete(request, board_id):
    # 게시글
    b = get_object_or_404(Board, pk=board_id)
    
    # 삭제 권한 확인
    if request.user.username != b.author.username:
        logout(request)
        return redirect("main_page")
    
    # 삭제
    b.delete()
    
    # 메시지
    messages.success(request, "게시글이 삭제되었습니다.")
    
    # 목록으로 이동
    return redirect("board:list")

# 수정, /board/<board_id/update/
def board_update(request, board_id):
    # 게시글
    b = get_object_or_404(Board, pk=board_id)
    
    # 수정 권한 확인
    if request.user.username != b.author.username:
        logout(request)
        return redirect("main_page")
    
    # 페이지 번호
    page = request.GET.get("page", 1)
    
    # 수정 폼   
    form = CreateForm(instance=b)
    
    # 템플릿으로 넘겨줄 정보
    context = {
        "page": page,
        "form": form,
        "board": b,
    }
    
    # POST
    if request.method == "POST":       
        # 수정 폼   
        form = CreateForm(request.POST)
        
        # 넘어온 값 검증
        if form.is_valid():
            cd = form.cleaned_data
            
            # 요약하기
            content_summary = summary(cd["content"])
            
            # 수정하기
            b.title = cd["title"]
            b.content = cd["content"]
            b.summary = content_summary
            b.save()
            
            # 메시지
            messages.success(request, "게시글이 수정되었습니다.")
            
            # 보기로 이동
            return redirect("board:read", b.id)    
    
    # 수정 화면
    return render(request, "board/update.html", context)

mysite/templates/board/create.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load my_filter %}

{% block content %}
<form id="createForm" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">등록</button>
        </div>
        <div class="col d-flex justify-content-end">
            <a href="{% url 'board:list' %}?{% query_string page=page %}" class="btn btn-danger">취소</a>
        </div>
    </div>
</form>
{% endblock %}

{% block script %}
<script>
    $("#createForm").validate({
        rules: {
            title: {
                required: true,
            },
            content: {
                required: true,
            },
        },
        messages: {
            title: {
                required: "제목을 입력해주세요.",
            },
            content: {
              required: "내용을 입력해주세요.",
            }
        },
        errorClass: "mt-2 text-danger",
        highlight: function(element) {
            $(element).addClass("is-invalid").removeClass("is-valid");
        },
        unhighlight: function(element) {
            $(element).addClass("is-valid").removeClass("is-invalid");
        },
        submitHandler: function (form) {
            form.submit();
        }  
    });
</script>
{% endblock %}

mysite/templates/board/list.html
{% extends "base.html" %}

{% load static %}
{% load my_filter %}

{% block content %}
<div class="row mb-3">
    <div class="col">
        <a class="btn btn-primary" href="{% url 'board:create' %}?{% query_string page=page %}">등록하기</a>
    </div>
    <div class="col d-flex justify-content-end">
        <!-- 검색 -->
        <form id="searchForm" method="get">
            <div class="input-group">
                <select class="form-select" name="where">
                    <option value="title" {% if where == "title" %} selected{% endif %}>제목</option>
                    <option value="content" {% if where == "content" %} selected{% endif %}>내용</option>
                    <option value="all" {% if where == "all" %} selected{% endif %}>전체</option>
                </select>
                <input type="text" class="form-control" name="kw" placeholder="검색어" value="{{ kw }}">
                <button type="submit" class="btn btn-primary">검색</button>
            </div>
        </form>
        <!--// 검색 -->
    </div>
</div>

<table class="table table-hover table-bordered">
    <thead>
        <tr class="table-primary">
            <th>번호</th>
            <th>제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
    </thead>
    <tbody>
    {% if board_list %}
        {% for board in board_list %}
            <tr>
                <!-- 번호 = 전체개수 - 시작인덱스 - 현재인덱스 + 1 -->
                <td>{{ board_list.paginator.count|sub:board_list.start_index|sub:forloop.counter0|add:1 }}</td>
                <td>
                    {% if board.created_at|is_new %}
                        <span class="badge bg-danger">new</span>
                    {% endif %}
                    <a href="{% url 'board:read' board.id %}?{% query_string page=page %}">{{ board.title }}</a>
                    <span class="ms-3 badge bg-success" data-bs-toggle="collapse" data-bs-target="#summary{{ board.id }}" aria-expanded="true" aria-controls="summary{{ board.id }}">요약보기</span>
                </td>
                <td>{{ board.author.first_name|change_name }}</td>
                <td>{{ board.created_at|date:"Y-m-d H:i" }}</td>
            </tr>
            <tr id="summary{{ board.id }}" class="accordion-collapse collapse">
                <td colspan="4">{{ board.summary }}</td>
            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="4" class="text-center">내용이 없습니다.</td>
        </tr>
    {% endif %}
    </tbody>
</table>

<!-- 페이징 -->
<nav>
    <ul class="pagination">
        <!-- 처음 -->
        {% if board_list.number > 4 %}
        <li class="page-item">
            <a class="page-link" href="?{% query_string page=1 %}">처음</a>
        </li>
        {% endif %}
        <!--// 처음 -->

        <!-- 이전 페이지 -->
        {% if board_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{% query_string page=board_list.previous_page_number %}">이전</a>
            </li>
        {% endif %}
        <!--// 이전 페이지 -->
        
        <!-- 페이지 리스트 -->
        {% for page_number in board_list.paginator.page_range %}
            {% if page_number >= board_list.number|add:-3 and page_number <= board_list.number|add:3 %}
                {% if page_number == board_list.number %}
                <li class="page-item active">
                    <a class="page-link">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% query_string page=page_number %}">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        <!--// 페이지 리스트 -->
      
        <!-- 다음 페이지 -->
        {% if board_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{% query_string page=board_list.next_page_number %}">다음</a>
            </li>
        {% endif %}
        <!--// 다음 페이지 -->

        <!-- 마지막 -->
        {% if board_list.number < board_list.paginator.num_pages|add:-3 %}
        <li class="page-item">
            <a class="page-link" href="?{% query_string page=board_list.paginator.num_pages %}">마지막</a>
        </li>
        <!--// 마지막 -->
        {% endif %}
    </ul>
</nav>
<!-- // 페이징 -->
{% endblock %}

mysite/templates/board/read.html
{% extends "base.html" %}

{% load static %}
{% load my_filter %}

{% block content %}
<div class="card mb-3">
    <div class="card-header">
        {{ board.title }}
    </div>
    <div class="card-body">
        <div class="mb-3">
            작성자: {{ board.user.username|change_name }},  작성일: {{ board.created_at|date:"Y-m-d H:i" }}
        </div>
        <div>{{ board.content|safe }}</div>
    </div>    
</div>
<div class="row">
    <div class="col">
        <a href="{% url 'board:list' %}?{% query_string page=page %}" class="btn btn-primary">목록</a>
    </div>
    {% if board.author.username == user.username %}
    <div class="col d-flex justify-content-end">
        <a href="{% url 'board:update' board.id %}?{% query_string %}" class="btn btn-warning me-3">수정</a>
        <button class="btn btn-danger" id="btnDelete">삭제</button>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block script %}
<script>
    $('#btnDelete').on('click', function(){
        if(confirm("게시글을 삭제하시겠습니까?")){
            location.href = "{% url 'board:delete' board.id %}?{% query_string %}"
        }
    });
</script>
{% endblock %}

mysite/templates/board/update.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load my_filter %}

{% block content %}
<form id="createForm" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">수정</button>
        </div>
        <div class="col d-flex justify-content-end">
            <a href="{% url 'board:read' board.id %}?{% query_string page=page %}" class="btn btn-danger">취소</a>
        </div>
    </div>
</form>
{% endblock %}

{% block script %}
<script>
    $("#createForm").validate({
        rules: {
            title: {
                required: true,
            },
            content: {
                required: true,
            },
        },
        messages: {
            title: {
                required: "제목을 입력해주세요.",
            },
            content: {
              required: "내용을 입력해주세요.",
            }
        },
        errorClass: "mt-2 text-danger",
        highlight: function(element) {
            $(element).addClass("is-invalid").removeClass("is-valid");
        },
        unhighlight: function(element) {
            $(element).addClass("is-valid").removeClass("is-invalid");
        },
        submitHandler: function (form) {
            form.submit();
        }  
    });
</script>
{% endblock %}