mysite/board/urls.py
from django.urls import path

from board import views

app_name = "board"

urlpatterns = [
    path("", views.board_list, name="list"),
    path("create/", views.board_create, name="create"),
    path("<int:board_id>/", views.board_read, name="read"),
    path("<int:board_id>/delete/", views.board_delete, name="delete"),
    path("<int:board_id>/update/", views.board_update, name="update"),
]

mysite/common/urls.py
from django.urls import path

from common import views

app_name = "common"

urlpatterns = [
    path('login/', views.common_login, name='login'),
    path('logout/', views.common_logout, name='logout'),
    path('profile/', views.common_profile, name='profile'),
    path('password/', views.common_password, name='password'),
    path('register/', views.common_register, name='register'),
    path('find_username/', views.common_find_username, name='find_username'),
    path('reset_password/', views.common_reset_password, name='reset_password'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from common import views as common_views
from django.conf import settings
from django.conf.urls.static import static

def trigger_error(request):
    division_by_zero = 1 / 0
    
urlpatterns = [
    path('sentry-debug/', trigger_error),
    path("", common_views.main_page, name="main_page"),
    path('summernote/', include('django_summernote.urls')),
    path("admin/", admin.site.urls),
    path("common/", include("common.urls")),
    path("common2/", include("common2.urls")),
    path("board/", include("board.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/common/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.safestring import SafeString

# 로그인
class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            
    def as_div(self):
        return SafeString(super().as_div().replace("<div>", "<div class='mb-3'>"))
    
    username = forms.CharField(label="아이디")
    password = forms.CharField(label="비밀번호", widget=forms.PasswordInput())

# 회원가입
class RegisterForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            
    def as_div(self):
        return SafeString(super().as_div().replace("<div>", "<div class='mb-3'>"))
    
    username = forms.CharField(label="아이디")
    password = forms.CharField(label="비밀번호", widget=forms.PasswordInput())
    first_name = forms.CharField(label="이름")
    email = forms.EmailField(label="이메일")
        
# 아이디 찾기
class FindUsernameForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(FindUsernameForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            
    def as_div(self):
        return SafeString(super().as_div().replace("<div>", "<div class='mb-3'>"))
    
    first_name = forms.CharField(label="이름")
    email = forms.EmailField(label="이메일")

# 비밀번호 초기화
class ResetPasswordForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ResetPasswordForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    def as_div(self):
        return SafeString(super().as_div().replace("<div>", "<div class='mb-3'>"))
    
    username = forms.CharField(label="아이디")
    first_name = forms.CharField(label="이름")
    email = forms.EmailField(label="이메일")
    
# 정보 수정
class ProfileForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    def as_div(self):
        return SafeString(super().as_div().replace("<div>", "<div class='mb-3'>"))
    
    first_name = forms.CharField(label="이름")
    email = forms.EmailField(label="이메일")


# 비밀번호 수정
class PasswordForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(PasswordForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    def as_div(self):
        return SafeString(super().as_div().replace("<div>", "<div class='mb-3'>"))
    
    password = forms.CharField(label="비밀번호", widget=forms.PasswordInput())
    re_password = forms.CharField(label="비밀번호 확인", widget=forms.PasswordInput())

mysite/common/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from common.forms import FindUsernameForm, LoginForm, RegisterForm, ResetPasswordForm, ProfileForm, PasswordForm
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.decorators import login_required


# 메인 화면
def main_page(request):
    context = {}
    return render(request, "common/main.html", context)

# 로그인, /common/login/
def common_login(request):
    # 템플릿으로 넘겨줄 정보
    context = {}
        
    if request.method == "POST":
        # 로그인 폼
        form = LoginForm(request.POST)
        
        # 넘어온 값 검증
        if form.is_valid():
            cd = form.cleaned_data
            
            # 아이디에 해당하는 사용자 정보 조회
            user = authenticate(request, username=cd["username"], password=cd["password"])
            
            # 사용자 유무 확인    
            if user is None:
                context["form"] = form
                context["error_message"] = "아이디를 확인하세요."
                return render(request, "common/login.html", context)
                
            # 비밀번호 검증
            if not user.is_authenticated:
                context["form"] = form
                context["error_message"] = "비밀번호를 확인하세요."
                return render(request, "common/login.html", context)
            
            # 로그인 처리
            login(request, user)
        
            # 메인 화면으로 이동
            return redirect("main_page")
        else:
            context["form"] = form
            context["error_message"] = "입력정보를 확인하세요."
            return render(request, "common/login.html", context)
        
    # 로그인 폼
    form = LoginForm()
    context["form"] = form
    return render(request, "common/login.html", context)
    
# 로그아웃, /common/logout/
def common_logout(request):
    logout(request)
    return redirect("main_page")
    
# 프로필, /common/profile/
@login_required
def common_profile(request):
    # 템플릿으로 넘겨줄 정보
    context = {}
        
    if request.method == "POST":
        # 정보 수정 폼
        form = ProfileForm(request.POST)
        
        # 넘어온 값 검증
        if form.is_valid():
            cd = form.cleaned_data
            
            # 사용자 정보 조회
            exist_users = User.objects.exclude(pk=request.user.pk).filter(email=cd["email"])
            
            # 사용자 유무 확인    
            if exist_users.exists():
                context["profile_form"] = form
                context["profile_error_message"] = "이미 등록된 이메일입니다."
                return render(request, "common/profile.html", context)
            
            # 사용자 정보 변경
            request.user.email = cd["email"]
            request.user.first_name = cd["first_name"]
            request.user.save()
            
            context["profile_form"] = form
            context["password_form"] = PasswordForm()
            context["profile_success_message"] = "사용자 정보를 수정하였습니다."
            return render(request, "common/profile.html", context)
        
    # 정보 수정 폼
    context["profile_form"] = ProfileForm(initial={'first_name': request.user.first_name, 'email': request.user.email})
    context["password_form"] = PasswordForm()
    return render(request, "common/profile.html", context)
    
# 비밀번호 수정, /common/password/
@login_required
def common_password(request):
    # 템플릿으로 넘겨줄 정보
    context = {}
        
    if request.method == "POST":
        # 비밀번호 수정 폼
        form = PasswordForm(request.POST)
        
        # 넘어온 값 검증
        if form.is_valid():
            cd = form.cleaned_data
            
            # 사용자 정보 변경
            request.user.set_password(cd["password"])
            request.user.save()
            
            return redirect('common:login')
    
# 회원가입, /common/register/
def common_register(request):
    # 템플릿으로 넘겨줄 정보
    context = {}
        
    if request.method == "POST":
        # 회원가입 폼
        form = RegisterForm(request.POST)
        
        # 넘어온 값 검증
        if form.is_valid():
            register_cd = form.cleaned_data
            
            # 아이디에 해당하는 사용자 정보 조회
            user = User.objects.filter(username=register_cd["username"])
            
            # 사용자 유무 확인    
            if user is not None:
                context["form"] = form
                context["error_message"] = "사용중인 아이디입니다."
                return render(request, "common/register.html", context)
            
            # DB에 사용자 정보 등록
            user = User.objects.create(
                username=register_cd["username"], 
                password=make_password(register_cd["username"]), 
                first_name=register_cd["first_name"],
                email=register_cd["email"]
            )
            
            context["form"] = LoginForm()
            context["success_message"] = "사용자를 추가하였습니다. 로그인을 해주세요."
            return render(request, "common/login.html", context)
        
    # 회원가입 폼
    form = RegisterForm()
    context["form"] = form
    return render(request, "common/register.html", context)

# 아이디 찾기, /common/find_username
def common_find_username(request):
    # 템플릿으로 넘겨줄 정보
    context = {}
        
    if request.method == "POST":
        # 아이디 찾기 폼
        form = FindUsernameForm(request.POST)
        
        # 넘어온 값 검증
        if form.is_valid():
            cd = form.cleaned_data
            
            # 사용자 정보 조회
            user = User.objects.filter(first_name=cd["first_name"], email=cd["email"])
            
            # 사용자 유무 확인    
            if len(user) == 0:
                context["form"] = form
                context["error_message"] = "등록된 사용자가 없습니다."
                return render(request, "common/find_username.html", context)
            
            context["find_user"] = user[0]
            context["form"] = form
            context["success_message"] = "사용자를 찾았습니다."
            return render(request, "common/find_username.html", context)
        
    # 아이디 찾기 폼
    form = FindUsernameForm()
    context["form"] = form
    return render(request, "common/find_username.html", context)
    
# 비밀번호 초기화, /common/reset_password/
def common_reset_password(request):
    # 템플릿으로 넘겨줄 정보
    context = {}
        
    if request.method == "POST":
        # 비밀번호 초기화 폼
        form = ResetPasswordForm(request.POST)
        
        # 넘어온 값 검증
        if form.is_valid():
            cd = form.cleaned_data
            
            # 사용자 정보 조회
            user = User.objects.filter(username=cd["username"], first_name=cd["first_name"], email=cd["email"])
            
            # 사용자 유무 확인    
            if len(user) == 0:
                context["form"] = form
                context["error_message"] = "등록된 사용자가 없습니다."
                return render(request, "common/reset_password.html", context)
            
            # 비밀번호 초기화
            new_password = "1234"
            user[0].set_password(new_password)
            user[0].save()
            
            context["new_password"] = new_password
            context["form"] = form
            context["success_message"] = "비밀번호를 초기화했습니다."
            return render(request, "common/reset_password.html", context)
            
    # 비밀번호 초기화 폼
    form = ResetPasswordForm()
    context["form"] = form
    return render(request, "common/reset_password.html", context)

mysite/templates/common/find_username.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<div class="alert alert-danger col-md-4" role="alert">{{ error_message }}</div>
{% endif %}

{% if success_message %}
<div class="alert alert-success col-md-4" role="alert">
    <p>{{ success_message }}</p>
    <span>아이디: {{ find_user.username }}</span>
</div>
<a href="{% url 'common:login' %}" class="btn btn-primary">로그인</a>
{% else %}
<div class="card col-md-4">
    <div class="card-header">
        아이디 찾기
    </div>
    <form id="findUsernameForm" action="{% url 'common:find_username' %}" method="post">
        {% csrf_token %}
        <div class="card-body">
            {{ form.as_div }}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">아이디 찾기</button>
        </div>
    </form>
</div>
{% endif %}

{% endblock %}

{% block script %}
<script>
    $("#findUsernameForm").validate({
        rules: {
            first_name: {
                required: true,
                minlength: 2,
                maxlength: 4,
            },
            email: {
                required: true,
                email: true,
            },
        },
        messages: {
            first_name: {
                required: "필수 입력입니다.",
                minlength: jQuery.validator.format("2글자 이상, 4글자 이하로 입력해주세요."),
                maxlength: jQuery.validator.format("2글자 이상, 4글자 이하로 입력해주세요."),
            },
            email: {
              required: "필수 입력입니다.",
              email: "올바른 형식의 이메일을 입력하세요."
            }
        },
        errorClass: "mt-2 text-danger",
        highlight: function(element) {
            $(element).addClass("is-invalid").removeClass("is-valid");
        },
        unhighlight: function(element) {
            $(element).addClass("is-valid").removeClass("is-invalid");
        },
        submitHandler: function (form) {
            form.submit();
        }  
    });
</script>
{% endblock %}

mysite/templates/common/login.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<div class="alert alert-danger col-md-4" role="alert">{{ error_message }}</div>
{% endif %}

{% if success_message %}
<div class="alert alert-success col-md-4" role="alert">{{ success_message }}</div>
{% endif %}

<div class="card col-md-4">
    <div class="card-header">
        아이디 찾기
    </div>
    <form id="loginForm" action="{% url 'common:login' %}" method="post">
        {% csrf_token %}
        <div class="card-body">
            {{ form.as_div }}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">로그인</button>
            <a href="{% url 'common:find_username' %}" class="btn btn-success">아이디 찾기</a>
            <a href="{% url 'common:reset_password' %}" class="btn btn-danger">비밀번호 초기화</a>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
<script>
    $("#loginForm").validate({
        rules: {
            username: {
                required: true,
            },
            password: {
                required: true,
            },
        },
        messages: {
            username: {
                required: "필수 입력입니다.",
            },
            password: {
              required: "필수 입력입니다.",
            }
        },
        errorClass: "mt-2 text-danger",
        highlight: function(element) {
            $(element).addClass("is-invalid").removeClass("is-valid");
        },
        unhighlight: function(element) {
            $(element).addClass("is-valid").removeClass("is-invalid");
        },
        submitHandler: function (form) {
            form.submit();
        }  
    });
</script>
{% endblock %}

mysite/templates/common/main.html
{% extends 'base.html' %}

{% block content %}
메인 화면
{% endblock %}

{% block script %}
<script>
</script>
{% endblock %}

mysite/templates/common/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <!-- 정보 수정 -->
    <div class="col-md-4">
        {% if profile_error_message %}
        <div class="alert alert-danger" role="alert">{{ profile_error_message }}</div>
        {% endif %}

        {% if profile_success_message %}
        <div class="alert alert-success" role="alert">{{ profile_success_message }}</div>
        {% endif %}

        <div class="card">
            <div class="card-header">
                정보 수정
            </div>
            <form id="profileForm" action="{% url 'common:profile' %}" method="post">
                {% csrf_token %}
                <div class="card-body">
                    {{ profile_form.as_div }}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">정보 수정</button>
                </div>
            </form>
        </div>
    </div>
    <!-- 정보 수정 -->

    <!-- 비밀번호 수정 -->
    <div class="col-md-4">
        {% if password_error_message %}
        <div class="alert alert-danger" role="alert">{{ password_error_message }}</div>
        {% endif %}

        {% if password_success_message %}
        <div class="alert alert-success" role="alert">{{ password_success_message }}</div>
        {% endif %}

        <div class="card">
            <div class="card-header">
                비밀번호 수정
            </div>
            <form id="passwordForm" action="{% url 'common:password' %}" method="post">
                {% csrf_token %}
                <div class="card-body">
                    {{ password_form.as_div }}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">비밀번호 수정</button>
                </div>
            </form>
        </div>
    </div>
    <!--// 비밀번호 수정 -->
</div>

{% endblock %}

{% block script %}
<script>
    $("#profileForm").validate({
        rules: {
            first_name: {
                required: true,
                minlength: 2,
                maxlength: 4,
            },
            email: {
                required: true,
                email: true,
            },
        },
        messages: {
            first_name: {
                required: "필수 입력입니다.",
                minlength: jQuery.validator.format("2글자 이상, 4글자 이하로 입력해주세요."),
                maxlength: jQuery.validator.format("2글자 이상, 4글자 이하로 입력해주세요."),
            },
            email: {
                required: "필수 입력입니다.",
                email: "올바른 형식의 이메일을 입력하세요."
            }
        },
        errorClass: "mt-2 text-danger",
        highlight: function(element) {
            $(element).addClass("is-invalid").removeClass("is-valid");
        },
        unhighlight: function(element) {
            $(element).addClass("is-valid").removeClass("is-invalid");
        },
        submitHandler: function (form) {
            form.submit();
        }  
    });

    $("#passwordForm").validate({
        rules: {
            password: {
                required: true,
                minlength: 8,
                maxlength: 20,
            },
            re_password: {
                required: true,
                minlength: 8,
                maxlength: 20,
                equalTo: "#id_password"
            },
        },
        messages: {
            password: {
                required: "필수 입력입니다.",
                minlength: jQuery.validator.format("8글자 이상, 20글자 이하로 입력해주세요."),
                maxlength: jQuery.validator.format("8글자 이상, 20글자 이하로 입력해주세요."),
            },
            re_password: {
                required: "필수 입력입니다.",
                minlength: jQuery.validator.format("8글자 이상, 20글자 이하로 입력해주세요."),
                maxlength: jQuery.validator.format("8글자 이상, 20글자 이하로 입력해주세요."),
                equalTo: "비밀번호와 비밀번호 확인이 다릅니다."
            },
        },
        errorClass: "mt-2 text-danger",
        highlight: function(element) {
            $(element).addClass("is-invalid").removeClass("is-valid");
        },
        unhighlight: function(element) {
            $(element).addClass("is-valid").removeClass("is-invalid");
        },
        submitHandler: function (form) {
            form.submit();
        }  
    });
</script>
{% endblock %}

mysite/templates/common/register.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<div class="alert alert-danger col-md-4" role="alert">{{ error_message }}</div>
{% endif %}

{% if success_message %}
<div class="alert alert-success col-md-4" role="alert">{{ success_message }}</div>
{% endif %}

<div class="card col-md-4">
    <div class="card-header">
        회원 가입
    </div>
    <form id="registerForm" action="{% url 'common:register' %}" method="post">
        {% csrf_token %}
        <div class="card-body">
            {{ form.as_div }}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">회원 가입</button>
        </div>
    </form>
</div>

{% endblock %}

{% block script %}
<script>
    $("#registerForm").validate({
        rules: {
            username: {
                required: true,
                minlength: 5,
                maxlength: 20,
            },
            password: {
                required: true,
                minlength: 8,
                maxlength: 20,
            },
            first_name: {
                required: true,
                minlength: 2,
                maxlength: 4,
            },
            email: {
                required: true,
                email: true,
            },
        },
        messages: {
            username: {
                required: "필수 입력입니다.",
                minlength: jQuery.validator.format("5글자 이상, 20글자 이하로 입력해주세요."),
                maxlength: jQuery.validator.format("5글자 이상, 20글자 이하로 입력해주세요."),
            },
            password: {
                required: "필수 입력입니다.",
                minlength: jQuery.validator.format("8글자 이상, 20글자 이하로 입력해주세요."),
                maxlength: jQuery.validator.format("8글자 이상, 20글자 이하로 입력해주세요."),
            },
            first_name: {
                required: "필수 입력입니다.",
                minlength: jQuery.validator.format("2글자 이상, 4글자 이하로 입력해주세요."),
                maxlength: jQuery.validator.format("2글자 이상, 4글자 이하로 입력해주세요."),
            },
            email: {
                required: "필수 입력입니다.",
                email: "올바른 형식의 이메일을 입력하세요."
            }
        },
        errorClass: "mt-2 text-danger",
        highlight: function(element) {
            $(element).addClass("is-invalid").removeClass("is-valid");
        },
        unhighlight: function(element) {
            $(element).addClass("is-valid").removeClass("is-invalid");
        },
        submitHandler: function (form) {
            form.submit();
        }  
    });
</script>
{% endblock %}

mysite/templates/common/reset_password.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<div class="alert alert-danger col-md-4" role="alert">{{ error_message }}</div>
{% endif %}

{% if success_message %}
<div class="alert alert-success col-md-4" role="alert">
    <p>{{ success_message }}</p>
    <span>비밀번호: {{ new_password }}</span>
</div>
<a href="{% url 'common:login' %}" class="btn btn-primary">로그인</a>
{% else %}
<div class="card col-md-4">
    <div class="card-header">
        비밀번호 초기화
    </div>
    <form id="resetPasswordForm" action="{% url 'common:reset_password' %}" method="post">
        {% csrf_token %}
        <div class="card-body">
            {{ form.as_div }}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">비밀번호 초기화</button>
        </div>
    </form>
</div>
{% endif %}

{% endblock %}

{% block script %}
<script>
    $("#resetPasswordForm").validate({
        rules: {
            username: {
                required: true,
            },
            first_name: {
                required: true,
            },
            email: {
                required: true,
                email: true,
            },
        },
        messages: {
            username: {
                required: "필수 입력입니다.",
            },
            first_name: {
                required: "필수 입력입니다.",
            },
            email: {
                required: "필수 입력입니다.",
                email: "올바른 형식의 이메일을 입력하세요."
            }
        },
        errorClass: "mt-2 text-danger",
        highlight: function(element) {
            $(element).addClass("is-invalid").removeClass("is-valid");
        },
        unhighlight: function(element) {
            $(element).addClass("is-valid").removeClass("is-invalid");
        },
        submitHandler: function (form) {
            form.submit();
        }  
    });
</script>
{% endblock %}